window.WATCHES = [
  {slug:"royal",ref:"5204X-001",name:"Royal Collection",tag:"Or Jaune 18k",
   tagline:"Split-Seconds Chronograph. Perpetual Calendar.",
   description:"An iconic masterpiece engineered for generations.",
   price:"CHF 248,000",availability:"By appointment · Geneva atelier",
   image:"collection-royal.jpg",macro:"gallery-1.jpg",
   movement:"craft-detail.jpg",caseStrap:"gallery-2.jpg",
   story:"A sovereign in solid gold. Roman numerals etched by hand into a sunburst dial. The Royal is the maison's quiet declaration of permanence.",
   movementStory:"Three hundred and eighty-four components arranged in column-wheel architecture. Anglage filed against the grain. Screws polished black under candlelight.",
   caseStory:"A 41mm white-gold case carved from a single ingot, paired with a navy textured strap and red stitching — a hand-stitched signature of the Geneva atelier.",
   highlights:[
     {title:"Split-Seconds Chronograph",desc:"Twin column wheels for true rattrapante timing."},
     {title:"Perpetual Calendar",desc:"Mechanical memory until the year 2100."},
     {title:"Moon Phase Display",desc:"Accurate to one day every 122 years."},
     {title:"Tachymeter Scale",desc:"Engraved on the inner bezel in gilt."},
     {title:"Sapphire Caseback",desc:"An open window onto the maker's hand."},
     {title:"65-Hour Power Reserve",desc:"Nearly three days of autonomy at rest."}],
   dial:["Sunburst navy blue dial","Applied white-gold markers","Faceted dauphine hands","Moonphase complication at 6 o'clock","Chronograph counters in silvered opaline"],
   caseDetails:["White gold case, 41mm","Navy textured calfskin strap","Red hand-stitched detailing","Fold-over deployant clasp"],
   specs:[["Case Diameter","41 mm"],["Thickness","11.2 mm"],["Water Resistance","30 m"],["Movement","Cal. AUR-CHR 29-535 PS Q"],["Power Reserve","65 hours"],["Jewels","34"],["Frequency","28,800 vph"],["Material","18k White Gold"],["Strap","Navy Alligator"]]},
  {slug:"heritage",ref:"1897H-002",name:"Heritage Edition",tag:"Cal. AUR-1897",
   tagline:"Manual-Winding. Small Seconds. Founder's Caliber.",
   description:"A faithful continuation of the original 1897 drawings.",
   price:"CHF 86,500",availability:"Available in select boutiques",
   image:"collection-heritage.jpg",macro:"gallery-2.jpg",
   movement:"craft-detail.jpg",caseStrap:"gallery-3.jpg",
   story:"Drawn from the founder's leather-bound notebooks. Every curve traced from Henri Aurelius' original 1897 sketches — restored, not reinterpreted.",
   movementStory:"A manual-winding caliber assembled to the original geometry. Côtes de Genève hand-applied. Black-polished steelwork rendered in candlelight.",
   caseStory:"A 38mm rose-gold case in vintage proportions, set on a hand-stitched chocolate alligator strap with a pin buckle — quiet, restrained, eternal.",
   highlights:[
     {title:"Founder's Caliber",desc:"Faithful to the original AUR-1897."},
     {title:"Small Seconds",desc:"Subdial at 6 o'clock in silvered opaline."},
     {title:"Hand Engraving",desc:"Caseback engraved by a single artisan."},
     {title:"Box Sapphire Crystal",desc:"Domed in the manner of the era."},
     {title:"Solid Caseback",desc:"Engraved with the founder's signature."},
     {title:"60-Hour Power Reserve",desc:"Two and a half days at rest."}],
   dial:["Lacquered ivory grand-feu enamel dial","Painted Roman numerals","Heat-blued leaf hands","Railway minute track","Small seconds at 6 o'clock"],
   caseDetails:["Rose gold case, 38mm","Hand-stitched chocolate alligator strap","Vintage pin buckle in rose gold","Solid engraved caseback"],
   specs:[["Case Diameter","38 mm"],["Thickness","9.4 mm"],["Water Resistance","30 m"],["Movement","Cal. AUR-1897"],["Power Reserve","60 hours"],["Jewels","21"],["Frequency","21,600 vph"],["Material","18k Rose Gold"],["Strap","Chocolate Alligator"]]},
  {slug:"chrono",ref:"7150C-003",name:"Chronograph Series",tag:"Column-Wheel",
   tagline:"Column-Wheel Chronograph. Vertical Clutch.",
   description:"Precision in motion — for the modern legacy.",
   price:"CHF 42,900",availability:"Available in boutiques worldwide",
   image:"collection-chrono.jpg",macro:"gallery-3.jpg",
   movement:"craft-detail.jpg",caseStrap:"gallery-4.jpg",
   story:"A column-wheel chronograph in the purest tradition. Crisp pusher feel. Instant start. The instrument of choice for the modern connoisseur.",
   movementStory:"Vertical clutch architecture eliminates the stutter of the central seconds hand. Each column polished by hand, each spring tempered in-house.",
   caseStory:"A 42mm steel case, brushed and polished in alternating planes. A black calfskin strap with grey contrast stitching completes the silhouette.",
   highlights:[
     {title:"Column-Wheel Chronograph",desc:"The connoisseur's chronograph architecture."},
     {title:"Vertical Clutch",desc:"Instant, judder-free start."},
     {title:"Tachymeter Bezel",desc:"Engraved and lacquered in matte black."},
     {title:"Twin Subdials",desc:"30-minute and small seconds counters."},
     {title:"Sapphire Caseback",desc:"A view onto the column wheel in motion."},
     {title:"70-Hour Power Reserve",desc:"Nearly three days, fully wound."}],
   dial:["Anthracite vertical-brushed dial","Applied steel indices with luminous fill","Snailed chronograph counters","Red-tipped central chronograph hand","Date aperture at 6 o'clock"],
   caseDetails:["Stainless steel case, 42mm","Brushed and polished alternating finishes","Black calfskin strap with grey stitching","Folding deployant clasp"],
   specs:[["Case Diameter","42 mm"],["Thickness","12.8 mm"],["Water Resistance","100 m"],["Movement","Cal. AUR-CW 7150"],["Power Reserve","70 hours"],["Jewels","31"],["Frequency","28,800 vph"],["Material","Stainless Steel"],["Strap","Black Calfskin"]]},
  {slug:"signature",ref:"0050S-004",name:"Limited Signature",tag:"Édition de 50",
   tagline:"Skeleton Tourbillon. Fifty Pieces.",
   description:"Numbered, signed, and silent.",
   price:"CHF 612,000",availability:"Édition de 50 · Waiting list only",
   image:"collection-signature.jpg",macro:"gallery-4.jpg",
   movement:"craft-detail.jpg",caseStrap:"gallery-1.jpg",
   story:"A skeleton tourbillon limited to fifty pieces. Each numbered and signed by the master watchmaker who built it. Never to be reproduced.",
   movementStory:"A flying tourbillon at 6 o'clock cantilevered from a single bridge. The mainplate skeletonized to translucency, then hand-engraved across forty hours.",
   caseStory:"A 40mm platinum case set on a black alligator strap. The numbered edition mark — 'XX/50' — is engraved by hand into the lower flank.",
   highlights:[
     {title:"Flying Tourbillon",desc:"Cantilevered from a single bridge at 6 o'clock."},
     {title:"Skeletonized Mainplate",desc:"Hand-engraved across forty hours."},
     {title:"Platinum Case",desc:"950 platinum, mirror-polished."},
     {title:"Numbered Edition",desc:"XX/50, engraved by hand."},
     {title:"Sapphire Sandwich",desc:"Open dial and caseback."},
     {title:"72-Hour Power Reserve",desc:"Three days, single barrel."}],
   dial:["Open-worked sapphire dial","Faceted gold indices floating on the chapter ring","Heat-blued steel hands","Tourbillon cage visible at 6 o'clock","Hand-engraved bridges"],
   caseDetails:["Platinum 950 case, 40mm","Mirror-polished bezel","Black alligator strap, hand-stitched","Platinum deployant clasp"],
   specs:[["Case Diameter","40 mm"],["Thickness","10.6 mm"],["Water Resistance","30 m"],["Movement","Cal. AUR-T 0050"],["Power Reserve","72 hours"],["Jewels","27"],["Frequency","21,600 vph"],["Material","Platinum 950"],["Strap","Black Alligator"]]}
];
window.getWatch = (slug) => window.WATCHES.find(w=>w.slug===slug);
